## conda requirements for all packages needed to run the scanpy tutorials
# install with:  mamba env create -n scRNAseq2021 -f environment.yml
# or  with:  conda env create -n scRNAseq2021 -f environment.yml
# then run: source activate scRNAseq2021
name: scRNAseq2021

channels:
 - conda-forge
 - anaconda
 - bioconda
 - defaults
 - r
 - rdonnelly
 - psi4
 - free
 - fastchan
 - ccordoba12
 - grst
 - Eugene_T
 - letaylor

dependencies:
 - r-base
 - rstudio
 - bioconductor-scater
 - bioconductor-scran
 - bioconductor-singlecellexperiment
 - bioconductor-slingshot
 - bioconductor-tradeseq
 - bioconductor-destiny
 - bioconductor-rhdf5
 - bioconductor-fgsea
 - bioconductor-biomart
 - bioconductor-org.hs.eg.db
 - bioconductor-scdblfinder
 - bioconductor-biocsingular
 - bioconductor-singler
 - bioconductor-batchelor
 - bioconductor-scmap
# - bioconductor-glmgampoi
# - bioconductor-scrnaseq
 - r-scpred
 - r-pheatmap
 - r-harmony
 - r-msigdbr
 - r-rafalib
 - r-enrichr
 - r-devtools
 - r-biocmanager
 - r-dplyr
 - r-igraph
 - r-seurat>=3.1.2
 - r-umap
 - r-grr
 - r-hdf5r
 - r-bookdown
 - r-venn
 - r-uwot
 - r-optparse
 - r-fields
 - r-ggraph
 - r-checkmate
 - r-tidygraph
 - notebook
 - jupyter_contrib_nbextensions
 - nbconvert=5.6.1
 - python-annoy
 - multicore-tsne
 - requests
 - r-spam
 - r-stringi
 - wget
 - compilers
 - pip
 - pip:
   - annoy
   - mnnpy
   - scanpy
   - scanorama
   - numba
   - python-igraph
   - umap-learn==0.4.6
   - louvain
   - leidenalg
   - matplotlib-venn
   - scrublet
   - gseapy
   - gsea-api
   - pybiomart
   - scvelo

# Manual installation of packages that are not in conda:

# remotes::install_github('chris-mcginnis-ucsf/DoubletFinder', dependencies=FALSE)
# install.packages('clustree', dependencies=FALSE)
# remotes::install_github('satijalab/seurat-data', dependencies=FALSE)
